version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0/24
    volumes:
      - ./wireguard-config:/config
    restart: unless-stopped

  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks
    command:
      - ss-server
      - -s 127.0.0.1
      - -p 8388
      - -k your_password
      - -m aes-256-gcm
      - --plugin v2ray-plugin
      - --plugin-opts "server;path=/wireguard-ws"
    restart: unless-stopped
    ports:
      - "8388:8388"

networks:
  default:
    driver: bridge
