services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=auto
    volumes:
      - /storage/vpn/wireguard:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    extra_hosts:
      - "iptables-nft:iptables" # Passthrough for nftables compatibility
    restart: unless-stopped

